lib/koala_web/router.ex
defmodule KoalaWeb.Router do
  use KoalaWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(Koala.Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", KoalaWeb do
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    post("/", PageController, :login)
    post("/logout", PageController, :logout)
  end

  scope "/", KoalaWeb do
    pipe_through([:browser, :auth, :ensure_auth])

    get("/secret", PageController, :secret)

    resources "/events", EventController do
      resources("/entries", EntryController)
    end
  end
end

lib/koala/events/event.ex
defmodule Koala.Events.Event do
  use Ecto.Schema
  import Ecto.Changeset

  alias Koala.Entries.Entry

  @timestamps_opts type: :utc_datetime
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "events" do
    field :date, :utc_datetime
    field :expenses, :float
    field :location, :string

    has_many :entries, Entry, on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(event, attrs \\ %{}) do
    event
    |> cast(attrs, [:location, :expenses, :date])
    |> validate_required([:location, :expenses, :date])
  end
end

lib/koala/events/events.ex
defmodule Koala.Events do
  @moduledoc """
  The Events context.
  """

  import Ecto.Query, warn: false
  alias Koala.Repo

  alias Koala.Events.Event

  @doc """
  Returns the list of events.

  ## Examples

      iex> list_events()
      [%Event{}, ...]

  """
  def list_events do
    Event |> order_by(desc: :date) |> Repo.all()
  end

  @doc """
  Gets a single event.

  Raises `Ecto.NoResultsError` if the Event does not exist.

  ## Examples

      iex> get_event!(123)
      %Event{}

      iex> get_event!(456)
      ** (Ecto.NoResultsError)

  """
  def get_event!(id), do: Repo.get!(Event, id)

  @doc """
  Creates a event.

  ## Examples

      iex> create_event(%{field: value})
      {:ok, %Event{}}

      iex> create_event(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_event(attrs \\ %{}) do
    %Event{}
    |> Event.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a event.

  ## Examples

      iex> update_event(event, %{field: new_value})
      {:ok, %Event{}}

      iex> update_event(event, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_event(%Event{} = event, attrs) do
    event
    |> Event.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Event.

  ## Examples

      iex> delete_event(event)
      {:ok, %Event{}}

      iex> delete_event(event)
      {:error, %Ecto.Changeset{}}

  """
  def delete_event(%Event{} = event) do
    Repo.delete(event)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking event changes.

  ## Examples

      iex> change_event(event)
      %Ecto.Changeset{source: %Event{}}

  """
  def change_event(%Event{} = event) do
    Event.changeset(event, %{})
  end
end

lib/koala_web/controllers/event_controller.ex
defmodule KoalaWeb.EventController do
  use KoalaWeb, :controller

  alias Koala.Events
  alias Koala.Events.Event

  def index(conn, _params) do
    events = Events.list_events()
    render(conn, "index.html", events: events)
  end

  def new(conn, _params) do
    changeset = Events.change_event(%Event{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"event" => event_params}) do
    case Events.create_event(event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event created successfully.")
        |> redirect(to: event_path(conn, :show, event))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    render(conn, "show.html", event: event)
  end

  def edit(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    changeset = Events.change_event(event)
    render(conn, "edit.html", event: event, changeset: changeset)
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = Events.get_event!(id)

    case Events.update_event(event, event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: event_path(conn, :show, event))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    {:ok, _event} = Events.delete_event(event)

    conn
    |> put_flash(:info, "Event deleted successfully.")
    |> redirect(to: event_path(conn, :index))
  end
end

lib/koala_web/views/event_view.ex
defmodule KoalaWeb.EventView do
  use KoalaWeb, :view
end

lib/koala_web/templates/event/edit.html.eex
<h2>Edit Event</h2>

<%= render "form.html", Map.put(assigns, :action, event_path(@conn, :update, @event)) %>

<span><%= link "Back", to: event_path(@conn, :index), class: "btn btn-default btn-xs" %></span>

lib/koala_web/templates/event/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :location, class: "control-label" %>
    <%= text_input f, :location, class: "form-control" %>
    <%= error_tag f, :location %>
  </div>

  <div class="form-group">
    <%= label f, :expenses, class: "control-label" %>
    <%= number_input f, :expenses, step: "any", class: "form-control" %>
    <%= error_tag f, :expenses %>
  </div>

  <div class="form-group">
    <%= label f, :date, class: "control-label" %>
    <%= datetime_select f, :date, class: "form-control" %>
    <%= error_tag f, :date %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/koala_web/templates/event/index.html.eex
<h2>Senzual - Events</h2>

<span><%= link "New Event", to: event_path(@conn, :new), class: "btn btn-default btn-xs" %></span>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>Expenses</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for event <- @events do %>
      <tr>
        <td><%= DateTime.to_date event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.expenses %></td>

        <td class="text-right buttons-events-containers">
          <span><%= link "Show", to: event_path(@conn, :show, event), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Entries", to: event_entry_path(@conn, :index, event), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Edit", to: event_path(@conn, :edit, event), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Delete", to: event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/koala_web/templates/event/new.html.eex
<h2>New Event</h2>

<%= render "form.html", Map.put(assigns, :action, event_path(@conn, :create)) %>

<span><%= link "Back", to: event_path(@conn, :index), class: "btn btn-default btn-xs" %></span>

lib/koala_web/templates/event/show.html.eex
<h2>Show Event</h2>

<ul>

  <li>
    <strong>Location:</strong>
    <%= @event.location %>
  </li>

  <li>
    <strong>Expenses:</strong>
    <%= @event.expenses %>
  </li>

  <li>
    <strong>Date:</strong>
    <%= DateTime.to_date @event.date %>
  </li>

</ul>

<ul>
  <span><%= link "Edit", to: event_path(@conn, :edit, @event), class: "btn btn-default btn-xs" %></span>
  <span><%= link "Back", to: event_path(@conn, :index), class: "btn btn-default btn-xs" %></span>
  <span><%= link "Entries", to: event_entry_path(@conn, :index, @event), class: "btn btn-default btn-xs" %></span>
</ul>