lib/koala_web/router.ex
defmodule KoalaWeb.Router do
  use KoalaWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(Koala.Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", KoalaWeb do
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    post("/", PageController, :login)
    post("/logout", PageController, :logout)
  end

  scope "/", KoalaWeb do
    pipe_through([:browser, :auth, :ensure_auth])

    get("/secret", PageController, :secret)

    resources "/events", EventController do
      resources("/entries", EntryController)
    end
  end
end

lib/koala_web/views/layout_view.ex
defmodule KoalaWeb.LayoutView do
  use KoalaWeb, :view
end

lib/koala_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome to Senzual Night</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation" class="navBar">
          <%= if Guardian.Plug.current_resource(@conn) != nil do %>
            <span><%= link "Events", to: event_path(@conn, :index), class: "btn btn-default btn-xs nav" %></span>
            <span><%= link "Logout", to: page_path(@conn, :logout), method: :post, class: "btn btn-default btn-xs nav" %></span>
          <% else %>
          <% end %>
        </nav>
        <div class="logo"><%= link "", to: page_path(@conn, :login)%></div>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>